# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment
# spec.selector.matchLabels.app == spec.template.labels.app olmali !!! 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulutzincir-geth-1
  labels:
    app: bulutzincir-geth-1
spec:
  replicas: 1
  selector: # The .spec.selector field defines how the Deployment finds which Pods to manage
    matchLabels:
      app: bulutzincir-geth-1
  template: # The template field contains the following sub-fields:
    metadata:
      labels: #  Pods are labeled app: nginxusing the .metadata.labels 
        app: bulutzincir-geth-1
    spec:
      containers:
      - name: bulutzincir-geth
        image: bulutzincir-geth:0.1.0
        # tum env ler ayri verilmek yerine bir dosya uzerinden source edilebilir
        # .env dosyasini tek vermek daha kolay olabilir (bz-api'de olmayabilir ?)
        env:
          - name: GENESIS
            valueFrom:
              configMapKeyRef:
                name: bulutzincir-geth-config
                key: genesis
          - name: ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: bulutzincir-geth-config
                key: account
          - name: NET_ID
            valueFrom:
              configMapKeyRef:
                name: bulutzincir-geth-config
                key: netid
          # !!! keyfile ve password secret'da olmali 
          - name: KEYFILE
            valueFrom:
              configMapKeyRef:
                name: bulutzincir-geth-config
                key: keyfile
          - name: PW
            valueFrom:
              configMapKeyRef:
                name: bulutzincir-geth-config
                key: password

        ports:
        - containerPort: 8545
        resources:
          limits:
            cpu: "1"
            memory: "1G"
          requests:
            cpu: "0.5"
